# -*- coding: utf-8 -*-
# 檔案：C:\Genesis\RD_Center\SDK\System\Generate_API_Specs.py
# 狀態：實體 API 文件掃描器 (自動 AST 分析)

import os
import ast
import shutil

class APISpecScanner:
    def __init__(self, root_dirs, output_path, cloud_dest_dir=None):
        self.root_dirs = root_dirs
        self.output_path = output_path
        self.cloud_dest_dir = cloud_dest_dir
        self.specs = []

    def scan(self):
        for root_dir in self.root_dirs:
            if not os.path.exists(root_dir):
                continue
            for root, _, files in os.walk(root_dir):
                for file in files:
                    if file.endswith('.py') and not file.startswith('__'):
                        full_path = os.path.join(root, file)
                        rel_path = os.path.relpath(full_path, r"C:\Genesis")
                        self.parse_file(full_path, rel_path)

    def parse_file(self, full_path, rel_path):
        try:
            with open(full_path, 'r', encoding='utf-8') as f:
                content = f.read()
            tree = ast.parse(content, filename=full_path)
        except Exception:
            # Fallback if parsing fails due to syntax
            return

        file_spec = {
            "path": rel_path,
            "classes": [],
            "functions": []
        }

        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                class_info = {
                    "name": node.name,
                    "doc": ast.get_docstring(node) or "No docstring",
                    "methods": []
                }
                for item in node.body:
                    if isinstance(item, ast.FunctionDef):
                        args = [arg.arg for arg in item.args.args]
                        class_info["methods"].append({
                            "name": item.name,
                            "args": args,
                            "doc": ast.get_docstring(item) or "No docstring"
                        })
                file_spec["classes"].append(class_info)
            elif isinstance(node, ast.FunctionDef):
                args = [arg.arg for arg in node.args.args]
                file_spec["functions"].append({
                    "name": node.name,
                    "args": args,
                    "doc": ast.get_docstring(node) or "No docstring"
                })

        if file_spec["classes"] or file_spec["functions"]:
            self.specs.append(file_spec)

    def generate_markdown(self):
        md = []
        md.append("# 🏛️ Genesis SDK & Bricks API Reference Specification")
        md.append("This document is auto-generated by `Generate_API_Specs.py`. Do not edit directly.\n")
        
        for spec in self.specs:
            md.append(f"## 📂 File: `{spec['path']}`\n")
            
            if spec["classes"]:
                md.append("### Classes")
                for cls in spec["classes"]:
                    md.append(f"#### Class `{cls['name']}`")
                    md.append(f"> {cls['doc']}\n")
                    if cls["methods"]:
                        md.append("| Method Name | Arguments | Description |")
                        md.append("| --- | --- | --- |")
                        for m in cls["methods"]:
                            arg_str = ", ".join(m["args"])
                            doc_str = m["doc"].replace('\n', ' ')
                            md.append(f"| `{m['name']}` | `({arg_str})` | {doc_str} |")
                        md.append("")
            
            if spec["functions"]:
                md.append("### Functions")
                md.append("| Function Name | Arguments | Description |")
                md.append("| --- | --- | --- |")
                for f in spec["functions"]:
                    arg_str = ", ".join(f["args"])
                    doc_str = f["doc"].replace('\n', ' ')
                    md.append(f"| `{f['name']}` | `({arg_str})` | {doc_str} |")
                md.append("")
            
            md.append("---")

        with open(self.output_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(md))

        # Copy to G-Drive cloud destination if configured
        if self.cloud_dest_dir and os.path.exists(self.cloud_dest_dir):
            try:
                os.makedirs(self.cloud_dest_dir, exist_ok=True)
                shutil.copy(self.output_path, os.path.join(self.cloud_dest_dir, "sdk_api_reference.md"))
            except Exception:
                pass

if __name__ == "__main__":
    roots = [
        r"C:\Genesis\RD_Center\SDK",
        r"C:\Genesis\RD_Center\SDK_Bricks"
    ]
    out = r"C:\Genesis\sdk_api_reference.md"
    cloud_dest = r"G:\我的雲端硬碟\ITE GEMINI Pro雲端指揮中心\knowledge"
    
    scanner = APISpecScanner(roots, out, cloud_dest)
    scanner.scan()
    scanner.generate_markdown()
    print("[SUCCESS] API specifications generated successfully.")
